In [1]:
def my_function():
    pass

In [3]:
def my_sq(x):
    return x ** 2

In [4]:
my_sq(4)

16

In [7]:
assert my_sq(4) == 16

In [8]:
assert my_sq(4) == 25

AssertionError: 

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame({
    "a": [10, 20, 30],
    "b": [20, 30, 40]
})

In [11]:
df

a   b
0  10  20
1  20  30
2  30  40

In [13]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [14]:
type(df["a"])

pandas.core.series.Series

In [15]:
my_sq

<function __main__.my_sq(x)>

In [17]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [18]:
def my_exp(x, e):
    return x ** e

In [19]:
assert my_exp(4, 2) == 16

In [22]:
df["a"].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [24]:
df["a"].apply(lambda val: my_exp(val, 10))

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [25]:
df["a"].apply(lambda val: my_exp(10, val))

0                        10000000000
1              100000000000000000000
2    1000000000000000000000000000000
Name: a, dtype: object

In [26]:
def print_me(x):
    print(x)

In [27]:
print_me(1233)

1233


In [28]:
df["a"].apply(print_me)

10
20
30


0    None
1    None
2    None
Name: a, dtype: object

In [29]:
df

a   b
0  10  20
1  20  30
2  30  40

In [30]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [31]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [32]:
assert avg_3(0, 5, 10) == 5

In [33]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [34]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [35]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [36]:
import numpy as np

In [37]:
def avg_3_np(col):
    return np.mean(col)

In [38]:
df.apply(avg_3_np)

a    20.0
b    30.0
dtype: float64

In [39]:
df

a   b
0  10  20
1  20  30
2  30  40

In [41]:
df.apply(print_me, axis="columns")

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [42]:
def avg_2(x, y):
    return (x + y) / 2

In [44]:
df

a   b
0  10  20
1  20  30
2  30  40

In [43]:
(df["a"] + df["b"]) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [45]:
avg_2(df["a"], df["b"])

0    15.0
1    25.0
2    35.0
dtype: float64

In [46]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [47]:
avg_2_mod(df["a"], df["b"])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [49]:
df["a"] == 20

0    False
1     True
2    False
Name: a, dtype: bool

In [50]:
(df["a"] == 20).all()

False

In [51]:
(df["a"] == 20).any()

True

In [53]:
avg_2_mod(10, 20)

15.0

In [54]:
avg_2_mod(20, 20)

nan

In [55]:
import numpy as np

In [57]:
avg_2_mod_np = np.vectorize(avg_2_mod)

In [58]:
avg_2_mod_np(10, 20)

array(15.)

In [59]:
avg_2_mod_np(20, 20)

array(nan)

In [60]:
avg_2_mod_np(df["a"], df["b"])

array([15., nan, 35.])

In [62]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [63]:
v_avg_2_mod(df["a"], df["b"])

array([15., nan, 35.])

In [64]:
import numba

In [65]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [66]:
v_avg_2_mod_numba(df["a"], df["b"])

ValueError: Cannot determine Numba type of <class 'pandas.core.series.Series'>

In [68]:
df["a"].values

array([10, 20, 30], dtype=int64)

In [67]:
v_avg_2_mod_numba(df["a"].values, df["b"].values)

array([15., nan, 35.])

In [69]:
%%timeit
avg_2(df["a"], df["b"])

182 µs ± 2.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [70]:
%%timeit
v_avg_2_mod(df["a"], df["b"])

54.2 µs ± 1.6 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [71]:
%%timeit
v_avg_2_mod_numba(df["a"].values, df["b"].values)

10.6 µs ± 192 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
# exercise use the get_pop column on the rate column to assign a new column called population
tbl3 = pd.read_csv("data/table3.csv")

In [74]:
tbl3

country  year               rate
0  Afghanistan  1999       745/19987071
1  Afghanistan  2000      2666/20595360
2       Brazil  1999    37737/172006362
3       Brazil  2000    80488/174504898
4        China  1999  212258/1272915272
5        China  2000  213766/1280428583

In [75]:
def get_pop(rate):
    return int(rate.split("/")[1])

In [76]:
get_pop("123/138972423")

138972423